"""Removed is_active from User, transfered uploaded_file to Item

Revision ID: 611badd8c1a0
Revises: 7253266756bf
Create Date: 2026-07-30 16:37:57.292302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611badd8c1a0'
down_revision: Union[str, Sequence[str], None] = '7253266756bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('uploaded_file', sa.String(), nullable=True))
    op.drop_column('users', 'uploaded_file')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('uploaded_files', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('items', 'uploaded_file')
    # ### end Alembic commands ###
