"""Added cascade ondelete

Revision ID: 7253266756bf
Revises: f6383fd9ebbe
Create Date: 2026-07-29 23:14:24.708762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7253266756bf'
down_revision: Union[str, Sequence[str], None] = 'f6383fd9ebbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_owner_id_fkey'), 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key(op.f('items_owner_id_fkey'), 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
