"""Added type and category to Item, added balance with hybrid property to User

Revision ID: a3f1f20796f2
Revises: d2587651f9d4
Create Date: 2026-07-27 16:20:15.973113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f1f20796f2'
down_revision: Union[str, Sequence[str], None] = 'd2587651f9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'type')
    # ### end Alembic commands ###
