"""Added uploaded_files column in User

Revision ID: f6383fd9ebbe
Revises: a3f1f20796f2
Create Date: 2026-07-29 11:04:22.911531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6383fd9ebbe'
down_revision: Union[str, Sequence[str], None] = 'a3f1f20796f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uploaded_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uploaded_file')
    # ### end Alembic commands ###
